### ISSUE TITLE
Segfault on OSX/Debian in GCC/Clang builds.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-server#36]
During initial sync the process periodically terminates with:

```
Segmentation fault: 11
```

It restarts and continues fine, eventually hitting it again.

This could be resulting from a memory allocation failure due to limited RAM on this older machine (with 4GB RAM).

**Comment by evoskuil** [comment]
There are two reports of this happening on Linux now, including: http://pastebin.com/tj79Tw86

**Comment by thecodefactory** [comment]
I have been able to consistently reproduce a crash bug on initial sync using a 16GB Debian machine.  The compiled code uses gcc, and it happens with or without debugging enabled.

I am pasting the gdb output:
```
#0  __memcmp_sse2 () at ../sysdeps/x86_64/multiarch/../memcmp.S:136
#1  0x00007ffff701207d in equal<unsigned char> (__first2=0x14a9f61262119804 <error: Cannot access memory at address 0x14a9f61262119804>, 
    __last1=<optimized out>, 
    __first1=0x7ff4c401ac98 "u\260\263\306ܸ\017\252\307\341\334\314\356\325\330N\366\262j\006\313z?\221\031\224\235\315\177\357\"\200\020Q")
    at /usr/include/c++/4.9/bits/stl_algobase.h:822
#2  __equal_aux<unsigned char const*, unsigned char const*> (__first2=0x14a9f61262119804 <error: Cannot access memory at address 0x14a9f61262119804>, 
    __last1=<optimized out>, 
    __first1=0x7ff4c401ac98 "u\260\263\306ܸ\017\252\307\341\334\314\356\325\330N\366\262j\006\313z?\221\031\224\235\315\177\357\"\200\020Q")
    at /usr/include/c++/4.9/bits/stl_algobase.h:838
#3  equal<unsigned char const*, unsigned char const*> (__first2=0x14a9f61262119804 <error: Cannot access memory at address 0x14a9f61262119804>, 
    __last1=<optimized out>, 
    __first1=0x7ff4c401ac98 "u\260\263\306ܸ\017\252\307\341\334\314\356\325\330N\366\262j\006\313z?\221\031\224\235\315\177\357\"\200\020Q")
    at /usr/include/c++/4.9/bits/stl_algobase.h:1059
#4  compare (this=<synthetic pointer>, key=...) at ./include/bitcoin/blockchain/impl/htdb_slab_list_item.ipp:96
#5  get (key=..., this=<optimized out>) at ./include/bitcoin/blockchain/impl/htdb_slab.ipp:63
#6  libbitcoin::chain::transaction_database::get (this=0x7fffffffdc48, hash=...) at src/database/transaction_database.cpp:92
#7  0x00007ffff701f711 in operator() (slock=248, __closure=0x7ff4c401ac90) at src/impl/blockchain_impl.cpp:274
#8  std::_Function_handler<bool(long unsigned int), libbitcoin::chain::blockchain_impl::fetch_transaction(const hash_digest&, libbitcoin::chain::blockchain::fetch_handler_transaction)::<lambda(size_t)> >::_M_invoke(const std::_Any_data &, unsigned long) (__functor=..., __args#0=248)
    at /usr/include/c++/4.9/functional:2025
#9  0x00007ffff701aba9 in operator() (__args#0=<optimized out>, this=0x7fffe9ffacc0) at /usr/include/c++/4.9/functional:2439
#10 operator() (__closure=0x7fffe9ffacb8) at src/impl/blockchain_impl.cpp:166
#11 operator() (__closure=<optimized out>) at src/impl/blockchain_impl.cpp:175
#12 asio_handler_invoke<libbitcoin::chain::blockchain_impl::fetch(libbitcoin::chain::blockchain_impl::perform_read_functor)::<lambda()> > (function=...)
    at /usr/include/boost/asio/handler_invoke_hook.hpp:69
#13 invoke<libbitcoin::chain::blockchain_impl::fetch(libbitcoin::chain::blockchain_impl::perform_read_functor)::<lambda()>, libbitcoin::chain::blockchain_impl::fetch(libbitcoin::chain::blockchain_impl::perform_read_functor)::<lambda()> > (context=..., function=...)
    at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#14 boost::asio::detail::completion_handler<libbitcoin::chain::blockchain_impl::fetch(libbitcoin::chain::blockchain_impl::perform_read_functor)::<lambda()> >::do_complete(boost::asio::detail::io_service_impl *, boost::asio::detail::operation *, const boost::system::error_code &, std::size_t) (
    owner=<optimized out>, base=<optimized out>) at /usr/include/boost/asio/detail/completion_handler.hpp:68
#15 0x00007ffff6d87648 in complete (bytes_transferred=0, ec=..., owner=..., this=<optimized out>)
    at /usr/include/boost/asio/detail/task_io_service_operation.hpp:38
#16 do_run_one (ec=..., this_thread=..., lock=..., this=0x6bae20) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:384
#17 run (ec=..., this=0x6bae20) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:153
#18 run (this=<optimized out>) at /usr/include/boost/asio/impl/io_service.ipp:59
#19 operator() (__closure=<optimized out>) at src/utility/threadpool.cpp:51
#20 _M_invoke<> (this=<optimized out>) at /usr/include/c++/4.9/functional:1700
#21 operator() (this=<optimized out>) at /usr/include/c++/4.9/functional:1688
#22 std::thread::_Impl<std::_Bind_simple<libbitcoin::threadpool::spawn_once()::<lambda()>()> >::_M_run(void) (this=<optimized out>)
    at /usr/include/c++/4.9/thread:115
#23 0x00007ffff5838970 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#24 0x00007ffff6a690a4 in start_thread (arg=0x7fffe9ffb700) at pthread_create.c:309
#25 0x00007ffff4fa7ccd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

Here is the valgrind output (on a different run, but clearly in the same piece of code, indicating memory corruption):

```
==2933== Thread 8:
==2933== Invalid read of size 1
==2933==    at 0x4C2ED2C: __memcmp_sse4_1 (vg_replace_strmem.c:972)
==2933==    by 0x5A1F07C: equal<unsigned char> (stl_algobase.h:822)
==2933==    by 0x5A1F07C: __equal_aux<unsigned char const*, unsigned char const*> (stl_algobase.h:838)
==2933==    by 0x5A1F07C: equal<unsigned char const*, unsigned char const*> (stl_algobase.h:1059)
==2933==    by 0x5A1F07C: compare (htdb_slab_list_item.ipp:96)
==2933==    by 0x5A1F07C: get (htdb_slab.ipp:63)
==2933==    by 0x5A1F07C: libbitcoin::chain::transaction_database::get(std::array<unsigned char, 32ul> const&) const (transaction_database.cpp:92)
==2933==    by 0x5A29596: operator() (blockchain_impl.cpp:292)
==2933==    by 0x5A29596: std::_Function_handler<bool (unsigned long), libbitcoin::chain::blockchain_impl::fetch_transaction_index(std::array<unsigned char, 32ul> const&, std::function<void (std::error_code const&, unsigned long, unsigned long)>)::{lambda(unsigned long)#1}>::_M_invoke(std::_Any_data const&, unsigned long) (functional:2025)
==2933==    by 0x5A27BA8: operator() (functional:2439)
==2933==    by 0x5A27BA8: operator() (blockchain_impl.cpp:166)
==2933==    by 0x5A27BA8: operator() (blockchain_impl.cpp:175)
==2933==    by 0x5A27BA8: asio_handler_invoke<libbitcoin::chain::blockchain_impl::fetch(libbitcoin::chain::blockchain_impl::perform_read_functor)::<lambda()> > (handler_invoke_hook.hpp:69)
==2933==    by 0x5A27BA8: invoke<libbitcoin::chain::blockchain_impl::fetch(libbitcoin::chain::blockchain_impl::perform_read_functor)::<lambda()>, libbitcoin::chain::blockchain_impl::fetch(libbitcoin::chain::blockchain_impl::perform_read_functor)::<lambda()> > (handler_invoke_helpers.hpp:37)
==2933==    by 0x5A27BA8: boost::asio::detail::completion_handler<libbitcoin::chain::blockchain_impl::fetch(std::function<bool (unsigned long)>)::{lambda()#2}>::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (completion_handler.hpp:68)
==2933==    by 0x5D53647: complete (task_io_service_operation.hpp:38)
==2933==    by 0x5D53647: do_run_one (task_io_service.ipp:384)
==2933==    by 0x5D53647: run (task_io_service.ipp:153)
==2933==    by 0x5D53647: run (io_service.ipp:59)
==2933==    by 0x5D53647: operator() (threadpool.cpp:51)
==2933==    by 0x5D53647: _M_invoke<> (functional:1700)
==2933==    by 0x5D53647: operator() (functional:1688)
==2933==    by 0x5D53647: std::thread::_Impl<std::_Bind_simple<libbitcoin::threadpool::spawn_once()::{lambda()#1} ()> >::_M_run() (thread:115)
==2933==    by 0x723A96F: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20)
==2933==    by 0x5F9B0A3: start_thread (pthread_create.c:309)
==2933==    by 0x7A8BCCC: clone (clone.S:111)
==2933==  Address 0x217caf5e2a72b070 is not stack'd, malloc'd or (recently) free'd
```

**Comment by evoskuil** [comment]
Thanks for submitting. Given that the behavior seems universal, I'm planning to hold off on tagging the release until this is resolved.

**Comment by evoskuil** [comment]
This may help: https://github.com/libbitcoin/libbitcoin-server/commit/995d579edbeaa7f8535d3170a14df40985771cd2

**Comment by evoskuil** [comment]
Fingers crossed, still syncing, but it looks like this is resolved.

**Comment by digitsu** [comment]
I'm still getting this SegFault 11 error.  Seems to be at random times every 1000 or so blocks downloaded.  
I'm on x86_64-apple-darwin14.4.0 with Apple LLVM version 6.1.0 (clang-602.0.53)

**Comment by evoskuil** [comment]
I've been running a testnet build on OSX for over a week, fully synced currently at block `508,091`. I haven't seen any problems, but there is this open issue: https://github.com/libbitcoin/libbitcoin-server/issues/103

Are you hitting memory limits?

**Comment by digitsu** [comment]
I have 8gb system and after I closed down a lot of apps (browsers are a hog) freeing up memory and it seems to be working better. 

No segfault yet from 226000-236000 block



—
Regards,

**Comment by evoskuil** [comment]
If you monitor memory consumption and see it appear to grown unbounded you are probably hitting the memory stall. If it becomes too severe the process will be shut down. You can control this somewhat with config, specifically by reducing the number of peers you are syncing with. Once you get fully synced this is pretty rare. The next update will include some more configurable options that make it more manageable.

**Comment by digitsu** [comment]
I’ve been monitoring it and it never goes over 3.3gb used out of 8gb.  I doubt it is a run away memory leak or boundary it feels more like it doesn’t play well with some app and overstepped mem bounds and the more apps that are running concurrently the larger a chance that this will happen.

Looking forward to more options which I can try to make this go away.  (seg faulted again at 239xxx block)


The whole time

**Comment by evoskuil** [comment]
The application isn't known to leak, but there is a problem [documented here](https://github.com/libbitcoin/libbitcoin-server/issues/100) regarding message backlogging. But if you didn't surpass physical memory limits then it's unlikely that caused a process termination.

A stack trace would be very helpful. We have [this open issue](https://github.com/libbitcoin/libbitcoin-server/issues/103) for OSX only. Seems like this could be related, since we have no such issues on Linux or Windows.

**Comment by digitsu** [comment]
Here are is a stacktrace:
Most of the segfaults look like this:
(boost::asio::detail::kqueue_reactor::start_op)

**Comment by evoskuil** [comment]
That's the full trace?

**Comment by digitsu** [comment]
For that particular crash yes



—
Regards,

**Comment by digitsu** [comment]
I ran subsequent times under gdb but now it no longer segfaults. It seems that the crashes only occurred when the blocks less than #280xxx. 




Seems to be fine now thanks! Thought problem now is that I ran out of SSD space at 337xxx. 

Why does the db take upwards of 85gb?






—
Regards,

**Comment by evoskuil** [comment]
Are you running a build from newer sources?

The fully-indexed database is on the order of 100GB. The implementation is optimized for query performance, not for compact data storage.

**Comment by digitsu** [comment]
Yes, from the freshest github pull.

aaah good to know that.  It may be good to have that somewhere in the server wiki… 100GB is more than a laptop SSD can normally cough up ;)

**Comment by evoskuil** [comment]
I don't expect people to run servers on laptops, but certainly easy to add the info to the wiki.

It would be good to confirm whether latest updates are responsible for resolving the failure you were having.

Also, if you are syncing presently the latest update allows you to set checkpoints via the configuration file. You can significantly speed the sync by choosing a recent checkpoint.

**Comment by digitsu** [comment]
I’m all sync’d up now, (I bought an external 250gb SSD and I’m golden)
but now I’m getting new segfaults here is the osx crash logs



I’m also wondering what are the features of bx that requires the bs server to be running; it seems to work for most things like fetch-height without needing the server running.

thanks so much for all the help so far!!

**Comment by evoskuil** [comment]
The SSD will dramatically speed up mapping and especially unmapping of the memory-mapped database files. Shutdown will be much faster.

Your logs didn't make it to the post. If (from your other post) you are performing regular hard shutdowns you may have corrupted the database, in which case you would need to re-sync. A full node database is just a cache that can be rebuilt, so resiliency in the face of hard shutdown is not a priority.

On the other hand, there is a documented issue with OSX that I haven't had time to track down, so if you have a stack trace it might help.

BX connects to the p2p network for `send-tx-p2p` and to a single p2p node for `send-tx-node`. All of the other online commands connect to `libbitcoin-server` (or an older obelisk server). The default configuration uses an Airbitz server (one for mainnet and another for testnet). You can of course connect it to your own server in each of these cases.
